### ISSUE TITLE
paper download issue.

### ISSUE THREAD

**Issue by eprescott** [kohler/hotcrp#76] opened 2016-02-15 18:01 UTC
We are seeing a problem where anyone on the internal network can download all conference papers consistently.  But people outside of the network can only download them one or two at a time and even then it's hit or miss mostly on larger papers of 10M or bigger.

Apache is showing this error:

`Mon Feb 15 12:50:57.486946 2016] [:error] [pid 8622] [client <host_ip>:38616] PHP Warning:  Cannot modify header information - headers already sent in /var/www/<conference_name>/hotcrp/lib/documenthelper.php on line 446, referer: https://<hostname>/submissions/search?q=%28All%29&t=s`

So far that is the only error we are seeing.

**Comment by eprescott** [comment] 2016-02-15 18:47
Looks like it's being caught by ModSecurity

Message: Access denied with code 403 (phase 2). Operator EQ matched 0 at REQUEST_HEADERS. [file "/etc/httpd/modsecurity.d/activated_rules/modsecurity_crs_21_protocol_anomalies.conf"] [line "47"] [id "960015"] [rev "1"] [msg "Request Missing an Accept Header"] [severity "NOTICE"] [ver "OWASP_CRS/2.2.6"] [maturity "9"] [accuracy "9"] [tag "OWASP_CRS/PROTOCOL_VIOLATION/MISSING_HEADER_ACCEPT"] [tag "WASCTC/WASC-21"] [tag "OWASP_TOP_10/A7"] [tag "PCI/6.5.10"]
Action: Intercepted (phase 2)
Stopwatch: 1455527281622059 19627 (- - -)
Stopwatch2: 1455527281622059 19627; combined=788, p1=540, p2=205, p3=0, p4=0, p5=43, sr=143, sw=0, l=0, gc=0
Producer: ModSecurity for Apache/2.7.3 (http://www.modsecurity.org/); OWASP_CRS/2.2.6.
Server: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.1e-fips
Engine-Mode: "ENABLED"

**Comment by kohler** [comment] 2016-02-15 19:53
If you aren't running the current version, you should upgrade to that—if possible to git HEAD.

**Comment by eprescott** [comment] 2016-02-15 20:29
Thanks i'll update this was a fresh install from a bit over a month ago.  I did not see anything in the repo regarding updates that referenced anything like this.  I'll give it a shot and see if mod sec still complains.

**Comment by kohler** [comment] 2016-02-15 20:55
“PHP Warning: Cannot modify header information…” is a problem, and I think it's been fixed. If you are still seeing it on git HEAD report back.

**Comment by eprescott** [comment] 2016-02-16 17:11
We aplied the latest but are still seeing this error.  Allong with the error we are seeing that when we attempt to batch download occasionly they will download but most of the time will stop partway through at a random poing.. example 82.4 MB or 170.5 MB

[Tue Feb 16 12:06:51.712350 2016] [:error] [pid 24941] [client <client_ip>:63627] PHP Warning:  Cannot modify header information - headers already sent in /var/www/<sitename>/hotcrp/lib/filer.php on line 452, referer: https://<sitename.fqdn>/submissions/search?t=s&q=&qt=n&selector=1&post=sutvr714


Thanks.

**Comment by kohler** [comment] 2016-02-16 17:48
OK. The “Cannot modify header information” is the error I'm interested in. This does not happen on my deployments. In my experience, you get the “headers already sent” error when an *earlier* warning or error was reported to PHP's stdout. Your `php.ini` should have `display_errors` set to `stderr` or `Off`, and `error_reporting` set to E_ALL, and `log_errors` set to `On`. Do any other logged errors show up?

ModSecurity and OWASP errors I cannot help you debug; they might be local to your configuration. I really can help only if the problem is internal to hotcrp.

**Comment by eprescott** [comment] 2016-02-16 20:57
I have PHP., php.ini display_errors = stderr (for testing), error_reporting = E_ALL, log_errors = On 
No other errors are showing up.
I had disabled Mod Security to rule it out as well as the system firewalld, and we get the same error and responses when downloading batch papers. They time out only pulling down part of the file and then failing.

except now the error is:
[Wed Feb 10 10:08:08.519102 2016] [:error] [pid 16969] [client <client_ip>:62198] PHP Warning:  Cannot modify header information - headers already sent in /var/www/ics2016/hotcrp/lib/documenthelper.php on line 446, referer: https://<hostname_fqdn>/submissions/search?q=re%3Ame

**Comment by kohler** [comment] 2016-02-16 20:58
That error is from last week

**Comment by eprescott** [comment] 2016-02-16 20:59
yes sorry long day.  same line #.

[Tue Feb 16 15:31:39.092013 2016] [:error] [pid 4222] [client <clientip>:49382] PHP Warning:  Cannot modify header information - headers already sent in /var/www/<sitename>/hotcrp/lib/filer.php on line 452, referer: https://<hostnamefqdn>/submissions/search?q=%28All%29&t=s

**Comment by kohler** [comment] 2016-02-19 13:24
I gave this problem a little more thought, and looking at the code in Filer, I can see some potential reasons why the warning would happen. See dcf348eea06d67dede87aafb5f11f81d115cf515.

But if I'm right about that, then I also doubt that the warning is affecting your users. My guess is your users are seeing some timeout. The download takes too long and apache prematurely kills the connection. You may want, for example, to raise your `php.ini` `max_execution_time` setting.

https://www.devside.net/wamp-server/apache-and-php-limits-and-timeouts

**Comment by eprescott** [comment] 2016-02-19 16:38
We had bumped the max_execution_time to 1600 as a test with very slight improvement.
We did a number of packet captures at various sites to try to see what was going on and it seems to be mostly effecting sites with low latency, where people are on wifi or limited connection speed such as slow shred dsl.  We did still see 2 out of 15 failures on fast connections such as fast comcast connections.  With today's pull it's 2 out of 25 on a fast comcast. I'll have my reviewers test it some more.  

 The last update two days ago did not fix the download timeout/failure. But with the update we did see expected download size go away, so the browser was unaware of what size it was expecting,  and zip files were unable to be opened under windows or mac with the default extractors, but could be opened with Stuffit or 7-zip,.  That problem seem to be fixed with today's pull.   I was about to create a ticket for that issue as well.

**Comment by kohler** [comment] 2016-02-24 15:45
I'm going to close this for now; if you find a HotCRP bug please feel free to reopen. If you're finding that downloads tend to die after (say) 5 minutes exactly, then that's a hint there's a timeout. For instance perhaps Apache's TimeOut parameter.

**Closed by kohler** 2016-02-24 15:45 UTC
