### ISSUE TITLE
Submitted review rating not shown on paper page

### ISSUE THREAD

**Issue by bondhugula** [kohler/hotcrp#110] opened 2017-10-29 11:15 UTC
When a reviewer submits a review rating, although the hotcrp system appears to record it, the submitted rating isn't shown on subsequent visits to the paper's page. The drop down box in such cases still lists the default  "average" rating. This makes it hard to verify for which review the rating was submitted, and what it was. The paper could still be searched for with "re:<reviewer_name>  rate:<+/->

**Comment by bondhugula** [comment] 2017-10-29 12:26
Note: this doesn't happen with all papers, but some specific ones. It's not clear what's special with these.

**Comment by kohler** [comment] 2017-11-07 13:00
Hi, is this on hotcrp.com? If so what conference? Feel free to contact me on email.

**Comment by kohler** [comment] 2017-11-08 15:47
Thanks for the bug report, the issue is fixed in ffb72cd259cb0c426661d113334380d9e75f83a8

**Closed by kohler** 2017-11-08 15:47 UTC
